logging:
    file: /log/boot-doc.log
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql:
                            BasicBinder: trace
server:
    port: 8848
spring:
    application:
        name: spirng-boot-rabbitmq
    datasource:
        hikari:
            connection-timeout: 30000
            idle-timeout: 180000
            max-lifetime: 1800000
            maximum-pool-size: 10
            minimum-idle: 3
            pool-name: SpringBootHikariCP
        password: ''
        url: jdbc:mysql://localhost:3306/cms?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
            write-dates-as-timestamps: false
        time-zone: GMT+8
    jpa:
        databasePlatform: org.hibernate.dialect.MySQLDialect
        show-sql: true
    metrics:
        export:
            redis:
                prefix: beile
    rabbitmq:
        host: 127.0.0.1
        password: guest
        port: 5672
        username: guest
    redis:
        database: 0
        host: 127.0.0.1
        password: ''
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 0
